//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Area()
        {
            this.Data = new HashSet<Data>();
        }
    
        public int Id { get; set; }
        public string iso_code { get; set; }
        public string continent { get; set; }
        public string location { get; set; }
        public Nullable<double> population_density { get; set; }
        public Nullable<double> median_age { get; set; }
        public Nullable<double> aged_65_older { get; set; }
        public Nullable<double> aged_70_older { get; set; }
        public Nullable<double> gdp_per_capita { get; set; }
        public Nullable<double> extreme_poverty { get; set; }
        public Nullable<double> cardiovasc_death_rate { get; set; }
        public Nullable<double> diabetes_prevalence { get; set; }
        public Nullable<double> female_smokers { get; set; }
        public Nullable<double> male_smokers { get; set; }
        public Nullable<double> handwashing_facilities { get; set; }
        public Nullable<double> hospital_beds_per_thousand { get; set; }
        public Nullable<double> life_expectancy { get; set; }
        public Nullable<double> human_development_index { get; set; }
        public long population { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data> Data { get; set; }
    }
}
